name: CICD Pipeline 

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted
    permissions:
      contents: read
      dependency-graph: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile
      
  security-check:
    runs-on: self-hosted
    needs: compile
    permissions:
      contents: read
      dependency-graph: write

    steps:
    - uses: actions/checkout@v4
    # ... rest of security-check steps

  test:
    runs-on: self-hosted
    needs: security-check
    permissions:
      contents: read
      dependency-graph: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit Test Cases
      run: mvn test

  build_project_and_sonar_scan:
    runs-on: self-hosted
    needs: test
    permissions:
      contents: read
      dependency-graph: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # ... rest of the steps
